# Site settings
title: Gizmo Workshop
header-img: img/home-bg.jpg
email: ablancar@ic.ac.uk, j.pang10@alumni.imperial.ac.uk
copyright_name: strignus
description: Python / Raspberry Pi Learning!"
baseurl: "/PythonPractise/"
url: "https://starignus.github.io/PythonPractise/"
twitter_username: starignus
github_username:  starignus/PythonPractise
facebook_username:  starignus
email_username:  ariadna@starignus.com, j.pang10@alumni.imperial.ac.uk

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
